### ISSUE TITLE
Helix editor keymap

### ISSUE THREAD

**Issue by vrsko** [solomkinmv/shortcuts-disco#53]
Hi,

I've created a Helix keymap file, I'm sending it to you to paste into the shortcuts-data folder.

[helix.json](https://github.com/solomkinmv/shortcuts-disco/files/14943394/helix.json)

**Comment by solomkinmv** [comment]
Hey, thanks for contribution. I've created CR to run tests and validate shortcuts file based on schema https://github.com/solomkinmv/shortcuts-disco/pull/55.

Looks like shortcut schema is not fully supported. So far, I found following issues:
1. I don't support definition of alternative shortcuts in single `key` string. I'll consider adding it, but right now it should be 2 separate entries
2. Shortcuts with upper case characters need to be specified as `shift+t` instead of `T`
3. I'm using `+` to join symbols in one shortcut. In the provided json file I see `ctrl-u`. It should be `ctrl+u`
4. I don't have mapping for all special keys from the keymap in `key-codes.json`.

Can you fix those issues? Tests should catch all problems from the new file once you add it to `shortcuts-data`
